### ISSUE TITLE
Spamming the navigation icons causes errors

### ISSUE THREAD

**Issue by tabeckers** [Laixer/Swabbr-Android#216]
Quick succession of different tabs causes error messages saying the requested content could not be loaded. After this some pages aren't being reloaded until either a logout-login or some delay.

Spamming results in a HTTP 503 Service Unavailable. It appears we are able to crash the backend by spamming these buttons. The backend itself will then restart itself. This explains the delay before content can be loaded again.

**Comment by DonZandbergen** [comment]
Nee. Ik heb daar nog geen patroon / oorzaak gevonden.
OG kwam hiermee maar ik begrijp hem wel.
Goed navigerend door de app worden schermen op den duur niet meer geladen.
Dan moet de app worden gesloten en opnieuw gestart worden.

Ik zal het zelf ook even gaan testen, mogelijk weet ik straks meer.

**Comment by tabeckers** [comment]
@DonZandbergen Ik kan het inderdaad reproduceren als ik als een gek op de navigation knoppen blijf klikken (snel achter elkaar). Ik pas de issue aan.

**Comment by tabeckers** [comment]
This is probably related to #155. Currently when we spam the navigation icons we send an absolute ton of requests to the backend. Fixing #155 would prevent this. Note that some kind of rate limit would be a good idea, but fixing #155 first seems the most logical next step.
